### ISSUE TITLE
Not working on Lolipop

### ISSUE THREAD

**Issue by dekristo** [anhtuan98/uitanpr2#1]
Hi,

I tried to compile and run on my device but it stopped just after launch. I think that the problem came from the initialization of OpenCV.

**Comment by dekristo** [comment]
I managed to make it work by fixing the OpenCV dependdency.

**Comment by karkarolol** [comment]
@decristoyobs what exactly did you change and where? I'm a total noob to writing android apps in java but I'd love to be able to run this code on my phone.

**Comment by anhtuan98** [comment]
Thanks a lot
Sorry for late reply.
The message hidden in another folder in my mail box

Best wishes,

Tuan Nguyen, Ph.D.
Dean of Faculty of Computer Network and Communication
University of Information Technology
Linh Trung ward, Thu Duc District
Hochiminh City, Vietnam

**Comment by dekristo** [comment]
@karkaroloi i downloaded opencv for IOS from www.opencv.org. You have to follow installation instructions from the opencv site.
